### ISSUE TITLE
Travis failing to publish tag to pypi

### ISSUE THREAD

**Issue by lossyrob** [azavea/pystac#103]
Travis publishes tags to pypi via [this configuration](). It appears that the authentication information for the `rasterfoundry` user is [invalid](https://travis-ci.com/github/azavea/pystac/jobs/351793597#L730).

The goal of this issue is to track down why this deploy is failing and update the API key if necessary.

**Comment by lossyrob** [comment]
Pretty confused about this - I got an email saying v0.3.4 passed, and there's now a 0.3.4 package on pypi. But when I look at travis build history I still see the v0.3.4 branch as failing:

![Screen Shot 2020-06-21 at 12 18 03 PM](https://user-images.githubusercontent.com/2320142/85229751-a6624080-b3b9-11ea-9a76-d8bc7cc90088.png)

This is the successful build I was emailed about, which I don't see in travis history: https://travis-ci.org/github/azavea/pystac/builds/700450517

Perhaps an outcome of this issue will be to move off of Travis CI for build and publish, and onto GitHub Actions, which might have a more clear audit trail for builds and decreasing complexity by removing a 3rd party service.

**Comment by hectcastro** [comment]
I think that Travis is active on both `travis-ci.org` and `travis-ci.com`. It looks like the tagged commit for `.org` [succeeded](https://travis-ci.org/github/azavea/pystac/jobs/700450519), but the one for `.com` [failed](https://travis-ci.com/github/azavea/pystac/jobs/351793597). My suspicion is that the credentials were encrypted to target `.org` and not `.com`.

I attempted to disable builds in the `.com` platform (even though `.org` is seen as the legacy version) to reduce confusion. I agree on the true path forward being GitHub Actions, but think that a `pystac` migration would benefit from the CI transition work we plan to execute on next sprint in https://github.com/azavea/django-ecsmanage/issues/20.
