### ISSUE TITLE
Update PySTAC to use STAC 1.0.0.beta

### ISSUE THREAD

**Issue by simonkassel** [azavea/pystac#117]
- [x] Update schemas to 1.0.0-beta.2 versions and fix so that tests pass.

Changes to account for (from [CHANGELOG](https://github.com/radiantearth/stac-spec/blob/master/CHANGELOG.md#v100-beta2---2020-07-08)). Includes updates from both `v1.0.0-beta.1` and `v1.0.0-beta.2`.

Crossed out items did not require changes in PySTAC.

### Added
<ins>v1.0.0-beta.1 - 2020-07-08</ins>
- [x] ~JSON-schema file in the Point Cloud extension.~

<ins>v1.0.0-beta.2 - 2020-07-08</ins>
- [x] ~'alternate' as a listed 'rel' type with recommended 'text/html' to communicate there is an html version.~
- [x] ~Added a code of conduct based on github's template.~
- [x] ~Overview document that gives a more explanatory discussion of the various parts of the spec and how they relate~
- [x] ~Several new sections to 'best practices' document.~
- [x] Added the ability to define Item properties under Assets (item-spec/item-spec.md) #122 
  - See [additional fields for assets](https://github.com/radiantearth/stac-spec/blob/master/item-spec/item-spec.md#additional-fields-for-assets) and the relevant [best practices](https://github.com/radiantearth/stac-spec/blob/master/best-practices.md#common-use-cases-of-additional-fields-for-assets) documentation.
- [x] Add proj:shape and proj:transform to the projections extension. (@lossyrob)
- [ ] Collection-level assets extension (see [extension docs](https://github.com/radiantearth/stac-spec/tree/master/extensions/collection-assets)) (@lossyrob)
- [x] ~Instructions on how to run check-markdown locally~
- [ ] Timestamps extensions (adds fields published, expires and unpublished)
- [x] `created` and `updated` can be used in the assets to specify the creation / update times of the assets. (@lossyrob)
- [ ] Tiled Assets extension, for representing data that has been split into tiles (@lossyrob)

### Changed
<ins>v1.0.0-beta.1 - 2020-07-08</ins>
- [x] Clarification on null geometries, making bbox not required if a null geometry is used. (@simonkassel )
- [x] Multiple extents (bounding boxes / intervals) are allowed per Collection (@simonkassel )

<ins>v1.0.0-beta.2 - 2020-07-08</ins>
- [x] ~Label extension types were clarified and types in README and JSON schema were brought into alignment~
- [x] ~Moved item recommendations to best practices, and added a bit more in item spec about 'search'~
- [x] Moved eo:gsd from eo extension to core gsd field in Item common metadata
asset extension renamed to item-assets and renamed assets field in Collections to item_assets (@simonkassel )
- [ ] item-assets extension only requires any two fields to be available, not the two specific fields title and type (@lossyrob)
- [x] datetime allows null as value, but requires start_datetime and end_datetime then (@lossyrob)
- [ ] Extensions sat, scientific and view: At least one field is required to be specified. (@lossyrob)
- [x] Single File STAC extension changed to be a complete STAC catalog + GeoJSON FeatureCollection that contains collections and items. (@lossyrob)
- [x] ~Improved several JSON Schemas~

### Removed
<ins>v1.0.0-beta.1 - 2020-07-08</ins>
- [x] ~Validation instructions~

<ins>v1.0.0-beta.2 - 2020-07-08</ins>
- [x] ~The API portion of STAC has been split off into a new repository: stac-api-spec and will start being versioned and released separately than the core STAC spec.~
- [x] ~proj4 string from proj extension~ (no need to do as we are adding proj extension this release)
- [x] ~Various warnings about how the spec is very early and likely will change.
implementations.md (migrated to https://stacspec.org) and how-to-help.md (migrated to https://github.com/stac-utils/stac-ecosystem).~
- [x] commons extension completely removed: Items should contain all properties and not default to a common set at the Collection level (@lossyrob)
- [x] ItemCollection removed from stac-spec core repo, will migrate to stac-api-spec as that is the only place it is used. (@simonkassel)

### Fixed
<ins>v1.0.0-beta.1 - 2020-07-08</ins>
- [x] ~Fixed several JSON Schemas~
- [x] ~Fixed examples~

<ins>v1.0.0-beta.2 - 2020-07-08</ins>
- [x] ~Datacube extension: cube:dimensions was not flagged as required.~ (Datacube extension not implemented)

**Comment by simonkassel** [comment]
It's unclear to me what this means:

> `created` and `updated` can be used in the assets to specify the creation / update times of the assets.

Does this mean these should be optional properties in asset objects? (Doesnt't appear to be the case in [the Asset spec](https://github.com/radiantearth/stac-spec/blob/4988a40f6071666d345e4a1c5adc9a6338973769/item-spec/item-spec.md#asset-object). Or should it just be a method that refers to the item created/updated properties?

**Comment by lossyrob** [comment]
> It's unclear to me what this means:
> 
> > `created` and `updated` can be used in the assets to specify the creation / update times of the assets.
> 
> Does this mean these should be optional properties in asset objects? (Doesn't appear to be the case in [the Asset spec](https://github.com/radiantearth/stac-spec/blob/4988a40f6071666d345e4a1c5adc9a6338973769/item-spec/item-spec.md#asset-object). Or should it just be a method that refers to the item created/updated properties?
> 
> Do you have a sense of what's going on here?

See [this commit](https://github.com/radiantearth/stac-spec/commit/9b597cd274fe77fc0a4877a21b17d2262e5b7207) - since `created` and `updated` are in the common metadata, and now assets can hold item properties, it specifies the meaning for those fields if they are on an asset. This should really only effect the pydocs once the item asset properties feature is implemented.

**Comment by lossyrob** [comment]
The remainder of the work here is unimplemented extensions:
- collection-assets
- timestamps
- tiled-assets
-  item-assets
- sat
- scientific

These should be implemented in their own issues. #124 is ready to go for a release candidate

**Comment by lossyrob** [comment]
1.0.0-beta.2 supported in 0.5.0-RC1 release; unimplemented extensions documented in follow-up issues.
