### ISSUE TITLE
Allow user-defined fields when creating STAC objects ?

### ISSUE THREAD

**Issue by matthewhanson** [azavea/pystac#120]
Finally getting around to using pystac!  I really like the STAC_IO feature, it was really easy to just get going with both public and private s3 buckets. And the explicit creation of classes for objects such as Extent, Assets is great as I think it better enables building of tools on top of this then the approach I took in sat-stac, which was a barebones wrapper around JSON. The advantage of sat-stac is that you have more flexibility defining your objects, so I thought I'd bring this up as a discussion.

The STAC spec doesn't explicitly state that fields not in the core spec or an extension make STAC invalid. I think the implication is there...if you have additional fields you *should* define them as a vendor extension and provide a JSON schema that can be used to validate. However, I'm of the belief that *should* means many users will forgo this step. And there's many cases in which that's a perfectly fine choice. If I am using STAC to consume and process some data and create output products, I may very well want to add some additional metadata that will be used by a downstream process. It's easy to add fields to a dictionary, writing JSON schema is not. In fact as a user I probably don't even care if my STAC has additional fields, as long as it is considered STAC valid and consumable by other STAC software. It can/should ignore those.

I posit that users may want to arbitrarily add fields to Catalogs, Collections, or Items and be able to open and access them through the PySTAC objects, and also write them by providing additional keywords to the STAC objects constructors.

As it is, I can only create new STAC objects by providing the strict set of keywords, and if I convert any read STAC object to a dictionary I will lose any additional fields I may have added (such as through the use of from_file or to_dict).

What do you think of allowing PySTAC to pass through arbitrary fields? It not only makes it easier for users to incorporate into their own workflows, but also makes it easier to use PySTAC across STAC versions, such as reading in and writing out different versions.

**Comment by lossyrob** [comment]
Hey @matthewhanson, thanks for the issue and for taking a look at PySTAC!

I agree that PySTAC should handle extra fields. I wrote up issue #35 to capture some of this - do you think that what's described there captures the need here?

From an API standpoint, I was thinking that there could be something like an `extra_properties` member on STACObjects; Item already has a "properties" member that will capture everything in the "properties" field of the JSON, hence the "extra" prefix.

So something like:

```javascript
{
  "stac_version": "1.0.0-beta.2",
  "id": "NAIP",
  "description": "Catalog of NAIP Imagery",
  "links": [
    { "rel": "self", "href": "https://www.fsa.usda.gov/naip/catalog.json" },
    { "rel": "child", "href": "https://www.fsa.usda.gov/naip/30087/catalog.json" },
    { "rel": "root", "href": "https://www.fsa.usda.gov/catalog.json" }
  ],
  "some_rando_prop": "here"
}
```

would translate to the Catalog's extra_properties:

```
> catalog.extra_properties['some_rando_prop']
here
```

and you could set extra properties in the same way:

```
> c = pystac.Catalog(...)
> c.extra_properties['another_rando_prop'] = 'also_here'
```

Any thoughts on that API design?

**Comment by matthewhanson** [comment]
This makes sense to me. So Item properties already capture anything extra, so it's really just top-level fields right?

In that case I'm not sure "properties" is the right term to use, as they aren't going to be under the "properties" field.  "extra_fields" ?

**Comment by lossyrob** [comment]
👍  I like `extra_fields` better.
