### ISSUE TITLE
Allow override of stac_version

### ISSUE THREAD

**Issue by matthewhanson** [azavea/pystac#121]
Pegging PySTAC to a stac version is a fine choice for most users. But there are several use cases where I may want to alter it, such as:

- New version of STAC is released and PySTAC isn't updated
- I want to read in multiple STAC catalogs from different versions and create a new catalog

When looking at the core spec, there are some versions that have no differences, and in the future we may see minimal differences in versions that could be handled via #120 .

My use case right now: I'm creating a STAC catalog using PySTAC for 0.9.0, but creating a catalog for 1.0.0-beta.2. Turns out there's really minimal to no differences (depending on the extensions used), so I'd like to create my catalog with `stac_version` set to 1.0.0-beta.2.  I can wait for the next release...or if #120 was in force I could create a catalog now that would be readable by the next release.

It would be great if I could override the STAC version without monkey-patching it, such as a STAC_VERSION envvar or keyword.

**Comment by lossyrob** [comment]
> I want to read in multiple STAC catalogs from different versions and create a new catalog

PySTAC actually reads any previous version of STAC and migrates to the latest version, so I don't think this should be an issue - as long as the new catalog you want to write is the same version that version of PySTAC you're using is pinned to. 

The use case for upping a PySTAC version for a minor release before the PySTAC version is released makes sense.

Would setting an environment variable, say `PYSTAC_STAC_VERSION_OVERRIDE`, be sufficient here? That should be an easy change to [this line](https://github.com/azavea/pystac/blob/develop/pystac/version.py#L4)

**Comment by matthewhanson** [comment]
Yes, I think the ability to override with an environment variable would be helpful

**Comment by lossyrob** [comment]
Ended up going with a slightly more complicated approach in #130. This allows the user to set the override version in `pystac.set_stac_version(version)` as well as in the environment variable.
