### ISSUE TITLE
Figure out relationship between extensions and collections

### ISSUE THREAD

**Issue by simonkassel** [azavea/pystac#24]
Open question: how do we handle extension properties in collections?

potentially create EOCollection class

**Comment by lossyrob** [comment]
This issue should address the implementation of this section of the Collections spec: https://github.com/radiantearth/stac-spec/blob/master/collection-spec/collection-spec.md#common-fields-and-standalone-collections

**Comment by lossyrob** [comment]
Addressed in #27
