### ISSUE TITLE
Proprietary collections can be written without license link

### ISSUE THREAD

**Issue by jisantuc** [azavea/pystac#49]
### Problem Description

See catalog in `s3://demo-mlhub-earth/panama-water-features-jan-apr-2019/` -- the collections have a `proprietary` license, but there's no license link in `links`.

### Expected Behavior or Output

pystac should get mad at me when I try to write an invalid catalog

**Comment by lossyrob** [comment]
To encapsulate the results of our in-person  conversation:

The spec says that a link to a proprietary license [`SHOULD` be included](https://github.com/radiantearth/stac-spec/blob/v0.8.1/collection-spec/collection-spec.md#collection-fieldsV) This means it's optional. PySTAC won't enforce optional fields; this seems like it would be a good  warning  for `stac-validator` to output as part  of STAC validation.
