### ISSUE TITLE
Datetime format doesn't work well with libraries expecting ISO8601 formatted strings

### ISSUE THREAD

**Issue by kbgg** [azavea/pystac#56]
While the STAC spec specifies that datetimes should be formatted according to [RFC 3339, section 5.6](https://tools.ietf.org/html/rfc3339#section-5.6), the space separator between the date and time causes some issues with libraries expecting an ISO8601 formatted string. Changing the separator to 'T' would make the datetime compliant with both RFC 3339, section 5.6 as well as ISO8601.

For example, currently a datetime is formatted like this `2019-01-01 00:00:00Z` and the updated datetime string would be formatted like this `2019-01-01T00:00:00Z`.

**Comment by lossyrob** [comment]
Thanks for the report - hope to get to this in the next week or so!
