### ISSUE TITLE
Store items in non-canonical path

### ISSUE THREAD

**Issue by palmerj** [azavea/pystac#59]
I want to create a self contained catalog that uses relative links, but overrides that items should be stored in subdirectories of their parent catalog. e.g I want

`/tmp/test-catalog/test_dataset_1/BD44_500_031096.json`

rather than 

`/tmp/test-catalog/test_dataset_1/BD44_500_031096/BD44_500_031096.json`

Is this possible? I tried setting the href paths manually with the `set_self_href` method on all STAC objects and not calling normalize_hrefs, but that didn't work. See example here: https://gist.github.com/palmerj/a78dc0b99da0720266ac19c736785802

**Comment by palmerj** [comment]
I see in https://github.com/azavea/pystac/blob/develop/pystac/catalog.py#L395 that using the canonical path is hard coded and can not be configured. Is this correct?

**Comment by lossyrob** [comment]
Hey @palmerj, sorry for the late reply - does the second example here help?

https://pystac.readthedocs.io/en/latest/concepts.html#normalizing-hrefs

If you are setting non-canonical paths, you can walk through the catalog and set the HREFs explicitly based on the information from the stac objects themselves.

In your example, [you are calling](https://gist.github.com/palmerj/a78dc0b99da0720266ac19c736785802#file-test_stac_contained-py-L57) `normalize_hrefs` before `save`, which will then reset the HREFs to the canonical format. Could that be why using `set_self_href` manually did not work?

**Comment by palmerj** [comment]
Thanks that link did help.

This is what I landed on :)

```python
a_catalog.add_child(collection)
catalog.normalize_hrefs("/tmp/test-catalog")
for item in catalog.get_all_items():
    self_link = item.get_single_link("self")
    if self_link:
        item.set_self_href(os.path.split(self_link.target)[0] + ".json")
catalog.save(catalog_type=stac.CatalogType.RELATIVE_PUBLISHED)
```

I've noticed a few of the method calls set_self_href and get_single_link are not documented in the API reference, hence I was having initial trouble. 

Thanks again
