### ISSUE TITLE
LabelItems require too much state tracking from users

### ISSUE THREAD

**Issue by jisantuc** [azavea/pystac#60]
## Problem Description

As currently implemented, it's challenging to find a place to put a LabelItem's asset. The workflow this prevents is creating a bunch of `LabelItem`s in memory, creating a `Collection` in memory, then adding that `Collection` and those `LabelItem`s later to a `Catalog`, which is only at the very end written to disk. Having nowhere to store the data while building the object up in memory makes fulfilling the following requirement from the STAC spec difficult:

> The Label Extension requires at least one asset that uses the key "labels". The asset will contain a link to the actual label data.

I don't know where it's going to go right now! :thinking: And I don't think it's great ergonomically to require a bunch of filesystem manipulation/writing to disk to build up a STAC. Any failures midway through the process then leave halfway complete catalogs lying around, which adds to my manual cleanup burden.

## Proposed solution

It would be nice to shift IO to the end of the world to the extent possible. One way to do this would be to initialize `LabelItem`s with a `FeatureCollection` that gets written out adjacent to the label item (and assets get updated) whenever the `LabelItem` is saved.

**Comment by lossyrob** [comment]
Can you explain a bit more about what in the workflow requires writing assets? You should be able to build any STAC object in memory without writing; assets can point to hrefs that don't yet exist, in-memory label items don't require a link to the 'labels' be added even (though that would cause invalid STAC if you did write it out).

> I don't think it's great ergonomically to require a bunch of filesystem manipulation/writing to disk to build up a STAC.

Agreed, and PySTAC is explicitly set up to enable in-memory manipulation and only a single write whenever the user is ready. If there's a situation where this isn't possible that's a definite issue, but having trouble seeing where that's happening based on the issue description.

**Comment by jisantuc** [comment]
> Can you explain a bit more about what in the workflow requires writing assets?

If I start with some label data (let's say a big ol' geojson or shapefile) and need to slice it up into label items referencing some imagery chips, I don't have a great place to put the relevant subsets of labels while I'm doing the rest of the processing. I can create a dictionary or something from all my label item ids pointing to data I guess? But that also creates a weird burden for tracking state that I then have to resolve later. I guess it's incorrect to say that it requires filesystem IO, but it is correct to say (I think) that I have to track a relationship _somewhere_ between LabelItems and their label data until I'm ready to write the STAC out.

Since LabelItems require assets and since the eventual location where the LabelItem will be written isn't necessarily known at the time that I create the LabelItem, I think it would be easier if `LabelItem`s in `pystac` gave me a nice slot to store my label data.

> assets can point to hrefs that don't yet exist

the issue here is that I don't even know where the asset is going to be when it does exist. I have to track the relationship between the LabelItem and its data and figure that out later, far from where I'm doing the work to create the LabelItem and its data.

> in-memory label items don't require a link to the 'labels' be added even (though that would cause invalid STAC if you did write it out).

I know we've talked previously about whether it's pystac's or the user's responsibility to ensure that they've created a valid STAC, but given that LabelItems _must_ have an asset, I think it makes sense for them to carry around the data that will back that asset if it's available. Some label items won't need to carry around their data, for instance if the asset is a pointer to an already existing remote file, but for building up STACs from other data I think that will frequently not be the case.

**Comment by lossyrob** [comment]
>  I think it would be easier if LabelItems in pystac gave me a nice slot to store my label data.

Ah ok, so you're saying you want to store a GeoJSON dict inside a LabelItem, instead of having a mapping between say the label item's ID and the dict of labels?

That's understandable, but one of the ideals for PySTAC is to be as simple of an implementation as possible, and to not implement anything that the spec doesn't dictate, with a few exceptions. This will keep the library as simple and clean as possible, and any additional functionality people want to implement can be made outside of the core library. In this way the burden of tracking state is explicitly externalized onto the user, but also keeps PySTAC clear of anything but what it's trying to nail down, which is implementing the STAC spec.

Why not store the GeoJSON labels in the `property` on the Item, as that's a the best place to slot in application-specific information to any STAC Item?

**Comment by jisantuc** [comment]
I'm not sure that "have existing data, want to make smaller data label items" is super application specific. It sounds like it would be a common use, but I'm probably in a bit of a bubble. I'm leery of throwing something that is required for me to end up with a valid STAC catalog into a free-form json field, given past adventures abusing free-form json, but I'll close for now until someone other than me isn't thrilled with how this feels.
