### ISSUE TITLE
Wrong absolute path while listing catalog

### ISSUE THREAD

**Issue by DariaSatco** [azavea/pystac#62]
Hi,

I have noticed a problem in absolute HREF construction. When I try to read a catalog from file using the relative path, the error occurs:

[Errno 22] Invalid argument: 'c://C:\\Users\\*****'

I checked the source files and it seems that the problem is in the **utils.py** in **make_absolute_href()** function. 

abs_path = os.path.abspath(os.path.join(start_dir, parsed_source.path))

abs_path already includes C:\\ , so there is no need to build:
'{}://{}{}'.format(parsed_start.scheme, parsed_start.netloc, abs_path)

If I comment the following:            

if parsed_start.scheme != '':
                return '{}://{}{}'.format(parsed_start.scheme,
                                          parsed_start.netloc, abs_path)

everything works fine for me!

Has anybody faced the similar problem?

**Comment by lossyrob** [comment]
This seems like an issue with Windows file paths. `make_absolute_href` will have to take that into account - thank you for pointing out this bug!
