### ISSUE TITLE
Update PySTAC to use STAC 0.9.0

### ISSUE THREAD

**Issue by lossyrob** [azavea/pystac#65]
- [x] Update schemas to 0.9.0 versions and fix so that tests pass.

Changes to account for (from [CHANGELOG](https://github.com/radiantearth/stac-spec/blob/v0.9.0/CHANGELOG.md))

Crossed out items did not require changes in PySTAC.

### Added
- [x] `data` role, as a suggestion for a common role for data files to be used in case data providers don't come up with their own names and semantics

- [x] ItemCollection requires `stac_version` field, `stac_extensions` has also been added
- [x] A `description` field has been added to Item assets (also Asset definitions extension)
- [x] Field `mission` to [Common Metadata fields](https://github.com/radiantearth/stac-spec/tree/v0.9.0/item-spec/common-metadata.md)
- [x] Extensions:
    - [ ] ~~[Version Indicators extension](https://github.com/radiantearth/stac-spec/tree/v0.9.0/extensions/version/README.md), new `version` and `deprecated` fields in STAC Items and Collections~~ (not implemented)
    - [ ] ~~Data Cube extension can be used in Collections, added new field `description`~~ (not implemented)
    - [x] [Asset Extension](https://github.com/radiantearth/stac-spec/tree/v0.9.0/extensions/asset/README.md): new `description` and `roles` fields
    - [ ] ~~New [Projection Extension](https://github.com/radiantearth/stac-spec/tree/v0.9.0/extensions/projection/README.md) to describe Items with Assets that have an associated geospatial projection~~ (not implemented)
    - [ ] ~~New [View Geometry Extension](https://github.com/radiantearth/stac-spec/tree/v0.9.0/extensions/view/README.md)~~(not implemented)
- [ ] ~~STAC API~~:
    - [ ] ~~Added the [Item and Collection API Version extension](https://github.com/radiantearth/stac-spec/tree/v0.9.0/api-spec/extensions/version/README.md) to support versioning in the API specification~~
    - [ ] ~~Run `npm run serve` or `npm run serve-ext` to quickly render development versions of the OpenAPI spec in the browser~~
- [x] [Basics](https://github.com/radiantearth/stac-spec/tree/v0.9.0/item-spec/common-metadata.md#basics) added to Common Metadata definitions with new `description` field for
Item properties
- [ ] ~~New fields to the `link` object to facilitate [pagination support for POST requests](https://github.com/radiantearth/stac-spec/tree/v0.9.0/api-spec/api-spec.md#paging-extension)~~ (STAC API)
- [ ] ~~Clarification text on HTTP verbs in STAC API~~ (STAC API)

### Changed
- [x] Collection field `property` and the merge ability moved to a new extension 'Commons'
- [ ] ~~Collection `summaries` merge array fields now~~
- [x] Moved angle definitions from extensions `eo` and new `view` extension
  - [ ] `eo:off_nadir` -> `view:off_nadir`
  - [ ] `eo:azimuth` -> `view:azimuth`
  - [ ] `eo:incidence_angle` -> `view:incidence_angle`
  - [ ] `eo:sun_azimuth` -> `view:sun_azimuth`
  - [ ] `eo:sun_elevation` -> `view:sun_elevation`

- [x] Support for [CommonMark 0.29 instead of CommonMark 0.28](https://spec.commonmark.org/0.29/changes.html)
- [x] Added attribute `roles` to Item assets (also Asset definitions extension), to be used similarly to Link `rel`
- [ ] ~~Updated API yaml to clarify bbox filter should be implemented without brackets. Example: `bbox=160.6,-55.95,-170,-25.89`~~

- [x] Several fields have been moved from extensions or item fields to the [Common Metadata fields](https://github.com/radiantearth/stac-spec/tree/v0.9.0/item-spec/common-metadata.md):
  - [x] `eo:platform` / `sar:platform` => `platform`
  - [x] `eo:instrument` / `sar:instrument` => `instruments`, also changed from string to array of strings
  - [x] `eo:constellation` / `sar:constellation` => `constellation`
  - [x] `dtr:start_datetime` => `start_datetime`
  - [x] `dtr:end_datetime` => `end_datetime`
- [ ] Extensions:
    - [ ] ~~Data Cube extension: Changed allowed formats (removed PROJ string, added PROJJSON / WKT2) for reference systems~~
    - [ ] ~~[Checksum extension](extensions/checksum/README.md) is now using self-identifiable hashes ([Multihash](https://github.com/multiformats/multihash))~~
    - [ ] ~~Changed `sar:type` to `sar:product_type` and `sar:polarization` to `sar:polarizations` in the [SAR extension](extensions/sar/README.md)~~
- [ ] ~~STAC API~~:
    - [ ] ~~The endpoint `/stac` has been merged with `/`~~
    - [ ] ~~The endpoint `/stac/search` is now called `/search`~~
    - [ ] ~~Sort Extension - added non-JSON query/form parameter format~~
    - [ ] ~~Fields extension has a simplified format for GET parameters~~
    - [ ] ~~`search` extension renamed to `context` extension. JSON object renamed from `search:metadata` to `context`~~
    - [ ] ~~Removed "next" from the search metadata and query parameter, added POST body and headers to the links for paging support~~
    - [ ] ~~Query Extension - type restrictions on query predicates are more accurate, which may require additional implementation support~~
- [x] Item `title` definition moved from core Item fields to [Common Metadata Basics](https://github.com/radiantearth/stac-spec/tree/v0.9.0/item-spec/common-metadata.md#basics) 
fields. No change is required for STAC Items.
- [ ] ~~`putFeature` can return a `PreconditionFailed` to provide more explicit information when the resource has changed in the server~~
- [ ] ~~[Sort extension](api-spec/extensions/sort) now uses "+" and "-" prefixes for GET requests to denote sort order.~~
- [ ] ~~Clarified how `/search` links must be added to `/` and changed that links to both GET and POST must be provided now that the method can be specified in links~~

### Removed
- [x] `version` field in STAC Collections. Use [Version Extension](https://github.com/radiantearth/stac-spec/tree/v0.9.0/extensions/version/README.md) instead
- [x] `summaries` field from Catalogs. Use Collections instead
- [x] Asset Types (pre-defined values for the keys of individual assets, *not* media types) in Items. Use the asset's `roles` instead
- [x] `license` field doesn't allow SPDX expressions any longer. Use `various` and links instead
- [ ] Extensions:
    - [x] `eo:platform`, `eo:instrument`, `eo:constellation` from EO extension, and `sar:platform`, `sar:instrument`, `sar:constellation` from the [SAR extension](https://github.com/radiantearth/stac-spec/tree/v0.9.0/extensions/sar/README.md)
    - [x] Removed from EO extension field `eo:epsg` in favor of `proj:epsg`
    - [x] `gsd` and `accuracy` from `eo:bands` in the [EO extension](https://github.com/radiantearth/stac-spec/tree/v0.9.0/extensions/eo/README.md)
    - [ ] ~~`sar:absolute_orbit` and `sar:center_wavelength` fields from the [SAR extension](https://github.com/radiantearth/stac-spec/tree/v0.9.0/extensions/sar/README.md)~~
    - [ ] ~~`data_type` and `unit` from the `sar:bands` object in the [SAR extension](https://github.com/radiantearth/stac-spec/tree/v0.9.0/extensions/sar/README.md)~~
    - [x] Datetime Range (`dtr`) extension. Use the [Common Metadata fields](https://github.com/radiantearth/stac-spec/tree/v0.9.0/item-spec/common-metadata.md) instead
- [ ] ~~STAC API~~:
    - [ ] ~~`next` from the search metadata and query parameter~~
- [ ] ~~In API, removed any mention of using media type `multipart/form-data` and `x-www-form-urlencoded`~~

### Fixed

- [x] The `license` field in Item and Collection spec explicitly mentions that the value `proprietary` without a link means that the data is private
- [x] Clarified how to fill `stac_extensions`
- [x] More clarifications; typos fixed
- [ ] ~~Fixed Item JSON Schema now `allOf` optional Common Metadata properties are evaluated~~
- [ ] ~~Clarified usage of optional Common Metadata fields for STAC Items~~
- [ ] ~~Clarified usage of paging options, especially in relation to what OGC API - Features offers~~
- [ ] ~~Allow Commonmark in asset description, as it's allowed everywhere else~~
- [ ] ~~Put asset description in the API~~
- [ ] ~~Fixed API spec regarding license expressions~~
- [ ] ~~Added missing schema in the API Version extension~~
- [ ] ~~Fixed links in the Landsat example in the collection-spec~~

**Comment by simonkassel** [comment]
@lossyrob many of these items are related to [common metadata](https://github.com/radiantearth/stac-spec/blob/568a04821935cc92de7b4b05ea6fa9f6bf8a0592/item-spec/common-metadata.md). I can't really quite figure out how this fits in vis-a-vis pystac. It seems like these are just recommended (?) fields within properties, which you can currently just pass in anyway. Should PySTAC have a specific understanding of them?

**Comment by lossyrob** [comment]
For Commons extension - right now we're reading the Collection properties for any item in order to collect the total properties for that item (see https://github.com/azavea/pystac/blob/develop/pystac/serialization/common_properties.py#L6).

This method should be changed to check the version of the item_dict. If it's 0.9 or greater, check to see if 'commons' is in the stac_extensions. If not, we can avoid the rest of the method and return the item properties.
