### ISSUE TITLE
Discussion: is PyStac useful for creating offline STAC Catalogs?

### ISSUE THREAD

**Issue by richpsharp** [azavea/pystac#91]
Hi, I was looking for a support forum but couldn't find one. I hope this is an okay place to ask for support. If not, could someone direct me to the appropriate place?

I've got a set of GeoTIFFs in a Google bucket that I will be adding to over time. I'd like to use STAC to organize them in a standard way for listing and searching. What I'd like to do is be able to create a local catalog then upload it to a public accessible bucket. I followed the tutorial here: https://pystac.readthedocs.io/en/latest/tutorials/how-to-create-stac-catalogs.html and got what I could from the docs.

I made a tracer script to see if this would do what I wanted to do: https://gist.github.com/richpsharp/77e390901c6c266c00f5c2333a835e48, but when I examine my `catalog.json` there are a lot of Windows path slashes. Here's a snippet:

```
{
    "id": "mygsstac",
    "stac_version": "0.8.1",
    "description": "mygsstac",
    "links": [
        {
            "rel": "root",
            "href": ".\\catalog.json",
            "type": "application/json"
        },
        {
            "rel": "item",
            "href": ".\\raster_a\\raster_a.json",
            "type": "application/json"
        },
...
```

I was hoping to see paths that would be compatible with URLs or perhaps I could set a "root" which all the other `href`s would be built locally from. I'm worried that I don't understand how to use STAC or PySTAC and what I'm doing is a little skewed. Either that or I'm missing a big "set base url" switch. Thank you for any help!

**Comment by lossyrob** [comment]
Hi @richpsharp, apologies for taking so long to reply.

Are you working on a window machine?

From what I can see the line:

```
catalog.normalize_hrefs('mygsstac')
```

in your script sets the root to a bare string - `mygsstac`. This should be an absolute path or a URL, something like `/mygsstac` or `gs://another-bucket`.

If this is still an issue for you and you'd like to try to solve it, happy to continue to talk through this on this issue or in the Gitter channel at https://gitter.im/azavea/pystac
